{% set name = "tethys-platform" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tethysplatform/tethys/archive/refs/tags/{{ version }}.tar.gz
  sha256: 466cd13770c6660f7b5e460daaf6e96fcba5d92cedcd93af8e0ccb9e6ee36406

build:
  noarch: python
  number: 0
  entry_points:
    - tethys = tethys_cli:tethys_command
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - bcrypt
    - PyShp
    - pyopenssl
    - docker-py
    - distro
    - postgresql
    - psycopg2
    - sqlalchemy =1.*
    - geoalchemy2
    - plotly
    - bokeh <3
    - tethys_dataset_services >=2.0.0
    - hs_restclient
    - owslib
    - requests
    - dask
    - tethys_dask_scheduler >=1.0.2
    - service_identity
    - condorpy
    - siphon
    - python-jose
    - pyjwt
    - arrow
    - isodate
    - django =3.2.*
    - channels =3.*
    - daphne =3.*
    - django-analytical
    - django-axes
    - django-filter
    - djangorestframework
    - django-bootstrap5
    - django-cors-headers
    - django-model-utils
    - django-guardian
    - django-gravatar2
    - django-json-widget
    - django-mfa2
    - django-recaptcha2
    - django-simple-captcha
    - django-session-security
    - django-termsandconditions
    - social-auth-app-django
    - selenium
    - coverage
    - factory_boy
    - pillow
    - pip
    - future
    - flake8
    - flake8-bugbear
    - git
    - setuptools_scm
    - openssl
    - conda
    - conda-libmamba-solver

test:
  requires:
    - pip
  imports:
    - tethys_apps
    - tethys_cli
    - tethys_compute
    - tethys_config
    - tethys_gizmos
    - tethys_portal
    - tethys_quotas
    - tethys_sdk
    - tethys_services
  commands:
    - tethys version
    - tethys gen portal_config --overwrite
    - tethys scaffold --defaults --overwrite test_app

about:
  home: http://www.tethysplatform.org/
  summary: A development platform for creating geospatial and scientific web applications.
  description: |
    Tethys Platform has been designed to lower the barrier to geospatial and 
    scientific web app development. Use it to deliver your models and data as 
    interactive web apps.
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: http://docs.tethysplatform.org/en/stable/
  dev_url: https://github.com/tethysplatform/tethys

extra:
  recipe-maintainers:
    - swainn
    - sdc50
